# Generated by Django 4.2.16 on 2024-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('android', 'Android'), ('data_scientist', 'Data Scientist')], max_length=20, null=True),
        ),
    ]
