# Generated by Django 4.2.16 on 2024-10-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_resume_parsed_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='parsed_data_id',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
